### ISSUE TITLE
Test our app #1

### ISSUE THREAD

**Issue by eliskavo** [helberan/team-project#16]

**Comment by eliskavo** [comment]
Find out if our app is possible to launch, try the links, and attempt to break our application

**Comment by ghost** [comment]
### Issues:
1) **Blocker**: There seems to be issue with typescript version required by different packages. Had to downgrade to version in order to run "npm install" command ("npm install --legacy-peer-deps" or "npm install --force" can be used, not recommended). **Just make it work** 🗡 

2) **Fix date picker in "Objednat se", user should be able to pick time.**

3) "Q&A" in footer navigates to "Ceník".
4) In 'Kontakt,' please make the textbox 'Vaše zpráva' larger so that the user can see what they have written."

Fix obvious formatting issues like buttons, textboxes, labels to close to each other...
+

5) Please center text in the footer (in light blue rectangle) so that it is in the middle  Text is closer to the bottom of the rectangle. You can see this formatting issue best on "Ceník", "Kontakt" and "Objednat se".

6) For smaller screens (or zoomed in screens) or mobile devices (mobile web), "Objendat se" button has formatting issue:
![Image](https://github.com/helberan/team-project/assets/166000152/4d4b98be-bd15-41f2-941f-6552e6bf2c1c)

7) Footer is to close to button "Objednat se online" in "Ceník" . 
8) Footer is to close to button "Date picker" in "Objednat se".

**Nice to have:**
9) When on a mobile device or a smaller screen, it would be nice if after clicking on the burger menu, the text below would be pushed down as well.

Example, how to simulate:
a) Navigate to "O nás".
b) Zoom in or switch to mobile device mode (under chrome internal  tools).
c) Click on burger menu

Actual behavior:
Menu covers text "Naše služby".

Expected:
Text "Naše služby" should be pushed down... so it is still readable.

10) Navigation indicator - navbar: it would be nice to determine by just a glance that I am navigated for example on "Ceník" in navbar itself. Maybe highlight the text when clicked on.

@eliskavo let me know if you want me to create tasks...
